[package]
name = "rust_wordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unidecode = "0.3.0"
rand = "0.8.4"
regex = "1"
numeric = "0.0.1"
